from pathlib import Path
from typing import Any, Dict
import json


def load_json(path: str | Path) -> Dict[str, Any]:
    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_payloads_from_files(output_root: str | Path) -> Dict[str, Any]:
    """
    For now, read the three JSON files generated by privacy_video pipeline.
    Later, this can be replaced with reading embedded payloads from media.
    """
    output_root = Path(output_root)

    return {
        "encrypted_metadata_file": load_json(output_root / "encrypted_metadata_file.json"),
        "region_package": load_json(output_root / "embedded_encrypted_region_package.json"),
        "object_key_registry": load_json(output_root / "object_symmetric_key_registry.json"),
    }